# -*- coding: utf-8 -*-
"""Attention_Economy_Intelligence_Engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16TuVN8OkMWu0hQa3w3xgV9BxsDqKNDCg
"""

!pip install pytrends prophet plotly -q

from pytrends.request import TrendReq
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

pytrend = TrendReq()

brands = [
    "OpenAI",
    "Perplexity AI",
    "Canva",
    "Grammarly",
    "Notion"
]

pytrend.build_payload(
    brands,
    timeframe='today 12-m'
)

data = pytrend.interest_over_time()

data.head()

data = data.drop(columns=['isPartial'])

data.reset_index(inplace=True)

data.head()

data.to_csv(
    "attention_data.csv",
    index=False
)

plt.figure(figsize=(15,6))

for brand in brands:
    plt.plot(
        data['date'],
        data[brand],
        label=brand
    )

plt.title("Brand Attention Trends")
plt.legend()
plt.show()

average_attention = {}

for brand in brands:
    average_attention[brand] = data[brand].mean()

avg_df = pd.DataFrame(
    average_attention.items(),
    columns=[
        "Brand",
        "Average_Attention"
    ]
)

avg_df

growth_rates = {}

for brand in brands:

    start = data[brand].iloc[0]
    end = data[brand].iloc[-1]

    growth = ((end-start)/start)*100

    growth_rates[brand] = growth

growth_df = pd.DataFrame(
    growth_rates.items(),
    columns=[
        "Brand",
        "Growth_Rate"
    ]
)

growth_df

attention_scores = []

for brand in brands:

    avg = average_attention[brand]

    growth = growth_rates[brand]

    score = (0.7 * avg) + (0.3 * growth)

    attention_scores.append(
        [brand, avg, growth, score]
    )

scores_df = pd.DataFrame(
    attention_scores,
    columns=[
        "Brand",
        "AverageAttention",
        "GrowthRate",
        "AttentionMomentumScore"
    ]
)

scores_df

scores_df = scores_df.sort_values(
    by="AttentionMomentumScore",
    ascending=False
)

scores_df

fig = px.bar(
    scores_df,
    x="Brand",
    y="AttentionMomentumScore",
    title="Attention Momentum Rankings"
)

fig.show()

top_brand = scores_df.iloc[0]["Brand"]

print(
    f"The strongest attention momentum belongs to {top_brand}."
)

!pip install prophet -q

from prophet import Prophet

forecast_data = data[
    ["date","OpenAI"]
].copy()

forecast_data.columns = [
    "ds",
    "y"
]

model = Prophet()

model.fit(forecast_data)

future = model.make_future_dataframe(
    periods=90
)

forecast = model.predict(
    future
)

model.plot(forecast)

scores_df.to_csv(
    "attention_scores.csv",
    index=False
)

from google.colab import files

files.download(
    "attention_data.csv"
)

files.download(
    "attention_scores.csv"
)